name: Bug Report
description: Report a problem.
title: Summary of what needs to be fixed.
labels: [bug]
assignees:
  - renatomaia
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
      - label: "I have searched the [existing issues](https://www.github.com/renatomaia/coutil/issues)."
        required: true
- type: textarea
  id: steps
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior, including code to be executed.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: Expected Behavior
    description: What did you expect to happen and why?
- type: textarea
  id: usage
  attributes:
    label: Use Case
    description: Overview of the actual use case where the problem was noticed, the consequences of the faulty behavior, and if there was a workaround.
- type: input
  id: coutil
  attributes:
    label: Coutil version
    description: What version of Coutil you are using?
    placeholder: Version name or a link to a commit
- type: input
  id: libuv
  attributes:
    label: libuv version
    description: What is the version of libuv you are using?
    placeholder: Version name or a link to a commit
- type: input
  id: luamemory
  attributes:
    label: LuaMemory version
    description: What is the version of LuaMemory you are using?
    placeholder: Version name or a link to a commit
- type: input
  id: luavararg
  attributes:
    label: LuaVararg version
    description: What is the version of module 'vararg' you are using?
    placeholder: Version name or a link to a commit
- type: input
  id: lua
  attributes:
    label: Lua version
    description: What is the version of Lua you are using?
    placeholder: Version name or a link to a commit
- type: input
  id: system
  attributes:
    label: Operating System
    description: |
      What operating system version are you using?
      On Windows, click Start button > Settings > System > About.
      On macOS, click the Apple Menu > About This Mac.
      On Linux, use lsb_release or uname -a.
    placeholder: |
      e.g. Windows 10 version 1909, macOS Catalina 10.15.7, or Ubuntu 20.04.
- type: dropdown
  id: arch
  attributes:
    label: Architecture
    description: What architecture are you using?
    options:
      - x64
      - ia32
      - arm64
      - Other (specify in "Steps To Reproduce")
