name: Bug Report
description: Report a problem.
title: Summary of what needs to be fixed.
labels: [bug]
assignees:
  - maia
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
      - label: "I have searched the [existing issues](https://www.github.com/renatomaia/coutil/issues)."
        required: true
- type: textarea
  id: steps
  attributes:
    label: Steps To Reproduce
    description: |
      Steps to reproduce the behavior,
      including code to be executed.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: Expected Behavior
    description: What did you expect to happen and why?
  validations:
    required: false
- type: textarea
  id: usage
  attributes:
    label: Use Case
    description: |
      Overview of the actual use case where the problem was noticed.
      the consequences of the faulty behavior,
      and if there was a workaround.
  validations:
    required: false
- type: input
  attributes:
    label: Coutil Version
    description: What version of Coutil are you using?
    placeholder: 2.0.0
  validations:
    required: true
- type: dropdown
  attributes:
    label: What operating system are you using?
    options:
      - Windows
      - macOS
      - Ubuntu
      - Other Linux
      - Other (specify below)
  validations:
    required: true
- type: input
  attributes:
    label: Operating System Version
    description: |
      What operating system version are you using?
      On Windows, click Start button > Settings > System > About.
      On macOS, click the Apple Menu > About This Mac.
      On Linux, use lsb_release or uname -a.
    placeholder: |
      e.g.
      Windows 10 version 1909,
      macOS Catalina 10.15.7,
      or Ubuntu 20.04
- type: dropdown
  attributes:
    label: What arch are you using?
    options:
      - x64
      - ia32
      - arm64 (including Apple Silicon)
      - Other (specify below)
- type: input
  attributes:
    label: Last known working Coutil version
    description: What is the last version of Electron this worked in, if applicable?
    placeholder: 1.0.0
