conncount = 64
msgcount = 512
msgtotal = 2*conncount*msgcount
msgsize = 512
msgbyte = "x"
msgdata = string.rep(msgbyte, msgsize)
replydata = "reply"
replysize = #replydata
host = "127.0.0.1"
port = 65432
